<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-ADMPVVC9" name="Tests.TechnicalCareCSRMuletoA" tests="7" failures="1" timestamp="01 dic 2017 04:20:56 GMT" time="448.904" errors="3">
  <testcase name="TS51117_CRM_Fase_3_Technical_Care_CSR_Muleto_Visualizacion_mensaje_en_caso_de_No_poseer_Muleto" time="61.320" classname="Tests.TechnicalCareCSRMuletoA"/>
  <testcase name="TS51110_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_si_no_se_ingresa_un_texto_puede_continuar_con_la_gestion" time="64.034" classname="Tests.TechnicalCareCSRMuletoA">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at Tests.TechnicalCareCSRMuletoA.TS51110_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_si_no_se_ingresa_un_texto_puede_continuar_con_la_gestion(TechnicalCareCSRMuletoA.java:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TS51110_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_si_no_se_ingresa_un_texto_puede_continuar_con_la_gestion -->
  <testcase name="TS51114_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_ingreso_del_NuMERO_de_Caso_para_Devolucion_de_muleto" time="56.212" classname="Tests.TechnicalCareCSRMuletoA"/>
  <testcase name="TS51111_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_contenido_campo_Accesorios" time="64.239" classname="Tests.TechnicalCareCSRMuletoA">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at Tests.TechnicalCareCSRMuletoA.TS51111_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_contenido_campo_Accesorios(TechnicalCareCSRMuletoA.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TS51111_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_contenido_campo_Accesorios -->
  <testcase name="TS51097_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_seleccion_de_uNO_del_listado" time="73.160" classname="Tests.TechnicalCareCSRMuletoA">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at Tests.TechnicalCareCSRMuletoA.TS51097_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_seleccion_de_uNO_del_listado(TechnicalCareCSRMuletoA.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TS51097_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_seleccion_de_uNO_del_listado -->
  <testcase name="TS51109_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_si_no_se_ingresa_un_texto_puede_continuar_con_la_gestion" time="63.445" classname="Tests.TechnicalCareCSRMuletoA">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at Tests.TechnicalCareCSRMuletoA.TS51109_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_si_no_se_ingresa_un_texto_puede_continuar_con_la_gestion(TechnicalCareCSRMuletoA.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TS51109_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_si_no_se_ingresa_un_texto_puede_continuar_con_la_gestion -->
  <testcase name="TS51088_CRM_Fase_3_Technical_Care_CSR_Muleto_Verificacion_Blacklist_negativo" time="66.494" classname="Tests.TechnicalCareCSRMuletoA"/>
</testsuite> <!-- Tests.TechnicalCareCSRMuletoA -->
